version: "3"

services:
  web:
    build: .
    ports:
      - "8080"
    environment:
      - VIRTUAL_HOST=localhost

  lb:
    image: jwilder/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=localhost
    depends_on:
      - web
    ports:
      - "80:80"
